---
- name: Retrieve credentials and create sessions
  hosts: aws_management
  gather_facts: yes
  vars:
    target_server: "{{ server_name | default('all') }}"

  tasks:
    - name: Retrieve credentials for specific server
      include_role:
        name: aws-secrets-manager
        tasks_from: retrieve
      vars:
        server_name: "{{ target_server }}"
      when: target_server != 'all'

    - name: Retrieve credentials for all servers
      include_role:
        name: aws-secrets-manager
        tasks_from: retrieve
      vars:
        server_name: "{{ item }}"
      loop: "{{ groups['onprem_servers'] }}"
      when: target_server == 'all'
