---
- name: Setup AWS Secrets Manager infrastructure
  hosts: aws_management
  gather_facts: yes
  vars_files:
    - ../group_vars/all.yml

  tasks:
    - name: Check AWS CLI configuration
      command: aws sts get-caller-identity
      register: aws_identity
      changed_when: false

    - name: Create IAM policy for secrets management
      community.aws.iam_policy:
        policy_name: "OnPremSecretsManager"
        policy_document: "{{ lookup('template', '../templates/iam-policy.json.j2') }}"
        state: present

    - name: Create initial secrets for on-prem servers
      include_role:
        name: aws-secrets-manager
        tasks_from: setup
